email = "you@example.com"
server = "review.px4.io"
connection_url = "udp://:14551"
logging_directory = "/home/jetson/logloader/logs"
uploaded_logs_file = "/home/jetson/logloader/uploaded_logs.txt"
upload_enabled = true
public_logs = false
