email = "jake@arkelectron.com"
server = "logs.px4.io"
connection_url = "udp://192.168.1.34:14550"
logging_directory = "logs"
uploaded_logs_file = "uploaded_logs.txt"
upload_enabled = true
public_logs = false
